name: "Build and Push docker image to Azure ACR"
description: "Build and push a docker image to Azure ACR, with caching"

inputs:
  bin:
    required: true
    description: "Binary to build"
  dockerfile:
    required: false
    description: "The path to the Dockerfile to use"
    default: Dockerfile
  version:
    required: true
    description: Docker image version
  image:
    required: true
    description: "Docker image name"
  registry:
    required: true
    description: "ACR Repository name"
  username:
    required: true
    description: "ACR Repository Username"
  password:
    required: true
    description: "ACR Repository Password"
  ssh:
    description: "SSH Auth Sock"
runs:
  using: "composite"
  steps:
    # Login to registry (ACR)
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Check Docker version exists
      id: check_version_exists
      uses: ForesightMiningSoftwareCorporation/docker-check-exists@v1
      with:
        repository: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        image_name: ${{ inputs.image }}
        version: ${{ inputs.version }}
    # Setup the runner to use Docker Buildkit
    - name: Set up Docker Buildx
      if: ${{ fromJSON(steps.check_version_exists.outputs.exists) == false }}
      uses: docker/setup-buildx-action@v1
    # Build and Push Image with Cache
    - name: Build & Push
      uses: docker/build-push-action@v2
      if: ${{ fromJSON(steps.check_version_exists.outputs.exists) == false }}
      with:
        context: .
        push: true
        file: ${{ inputs.dockerfile }}
        tags: |
          ${{ inputs.registry }}/${{ inputs.image }}:${{ steps.read_version.outputs.value }}
          ${{ inputs.registry }}/${{ inputs.image }}:latest
        ssh: ${{ inputs.ssh }}