name: "Login to private registries"
description: "Composite action to login to a private Cargo Registry"

inputs:
  private_key:
    required: false
    default: ""
    description: "Private Key to use for the registry index"
  name:
    required: true
    description: "Name to use for the registry login"
  token:
    required: true
    description: "Token to use for the registry login"
  additional_private_keys:
    default: ""
    description: "Additional private keys to add to the ssh-agent"
  cos_username:
    default: ""
    description: "Username to connect to cos"
  cos_password:
    default: ""
    description: "Password to connect to cos"
  cos_tenant:
    default: ""
    description: "Tenant to connect to cos"
  cos_subscription:
    default: ""
    description: "Subscription to connect to cos"
  host:
    default: ""
    description: "DEPRECATED"
runs:
  using: "composite"
  steps:
    - name: Access private registry
      uses: ForesightMiningSoftwareCorporation/ssh-agent@master
      if: inputs.private_key != '' || inputs.additional_private_keys != ''
      with:
        ssh-private-key: |
          ${{ inputs.private_key }}
          ${{ inputs.additional_private_keys }}

    - name: Add Shipyard and github known hosts
      shell: bash
      run: |
        echo "$HOME"
        if [ "$HOME" == "/github/home" ]; then
          SSH_DIR="/root/.ssh"
        else
          SSH_DIR="$HOME"/.ssh
        fi
        mkdir -p $SSH_DIR
        echo "ssh.shipyard.rs ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMZHl+2KB5/Ir7xv8JhR94y8z6yyPCx7Srat05nx0aQR" >> $SSH_DIR/known_hosts
        echo "ssh.shipyard.rs ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOIuHng3QDNSKrDt+t4HEDw7rU2PqvaE3/MCpNGE27hZPV2GBdJ3N5voNA6ri0bkNSUWusoEC01MiGF5SiP77WB7WoK874yMcYX7gURkssRTPFAcHl9ta91JKnSpFH4Zff7SFB+NPDuCSZ4jzPr/1b5wj28+Cy5qZpwoJgfOjgMCn2dDPDxuKymAzDqOxrBKambPASgbnroxcRBYw92VnBZ2jQ/5U3E4PzIgcgAfzRQOmRl/FrsJVKM24M5tQSRdyaiIxXNNRwSEkjWfjD2nS5uISoxpckd1L9/t6NYh/2w714A45XqiN3Ka+p5DJtfDLiGfGdPJc7B0QaTNhc51SxbvyYIWc9e+PJw2PAwsfCQMPd6SUKD/4WWKpa2v5B/uN3x0U637/cLR7ie/eq6/UGQNKy2WmPOkkQqayXk/1aVd3gDYzfmH3VPSvYzYAscXV8PVNwdM850gpMzmYsee35NIoiiILB0WfUfaomSIWq2lKIde9N/71TFk0viDGeqsU=" >> $SSH_DIR/known_hosts
        echo "ssh.shipyard.rs ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHnY0iOesuCz8QzWY4Bdz+jyXlzC0H/Jo2qnnAQRgDam/gER2tfJjBtrwoEJwC8i5/aMMMB501UB4qvK6sM8iz0=" >> $SSH_DIR/known_hosts
        echo "ssh.shipyard.rs ssh-dss AAAAB3NzaC1kc3MAAACBAJAezxuCdJK1UyCN+dvBvl+vchwAh2iuGOoS2euf0Bks+WSsut+Gx6JBtWDf1VHlMJ/xk2IyC2mRRqn39h7PTh7QXaGpJjJ9vhUhYkPgL7MRIHWvyXwwsMwtRL95xfE/5fEu1YQdlQkRQ1s41TIfujHRWJ/6Rhow35dP5FNGbGUNAAAAFQDvLcqjmyGj/HhfuUJ9bkjD8iuiawAAAIA7hWQBvOKDFw7XFzCqOzCEFZojuI3SNjw1LijIKUGQZUdAcjedNVlbwEWorGP/u8TRWKm0t0Tti0FTHnYM9GmagNJKbsOyFKNRAWnqLMMP3ObvdnTNumer1aBTPTDuzarf9KXxWxrjo8B+vlGC07cGfS9uonAIU3tGSPw6FwTMzgAAAIBLs4nneFwwf+ZkSuUmw+NOQXcrr6j65QRMqGDkRBSuQsQhMEh8LA0xUtechA+15Ra251RLWjSpwKzDKBz6FeLVoQeH0yulp2vvD29Ftw/q3wx1rhkG8fEXQ0RVUT5AXrYO9oz9mrLobz9kGKkbO5evanoJkfzwCvkHmb+iyS+4sQ==" >> $SSH_DIR/known_hosts
        echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=" >> $SSH_DIR/known_hosts

    - name: Use ssh for github dep
      shell: bash
      run: |
        echo '[url "ssh://git@github.com/ForesightMiningSoftwareCorporation/"]' >> $HOME/.gitconfig
        echo "  insteadOf = https://github.com/ForesightMiningSoftwareCorporation/" >> $HOME/.gitconfig
        echo '[url "ssh://git@github.com/foresightminingsoftwarecorporation"]' >> $HOME/.gitconfig
        echo "  insteadOf = https://github.com/foresightminingsoftwarecorporation" >> $HOME/.gitconfig
        echo '[url "ssh://git@github.com/orica-digital"]' >> $HOME/.gitconfig
        echo "  insteadOf = https://github.com/orica-digital" >> $HOME/.gitconfig
        echo '[url "ssh://git@github.com/orica-digital"]' >> $HOME/.gitconfig
        echo "  insteadOf = https://git@github.com/orica-digital" >> $HOME/.gitconfig
    - name: Login to shipyard private registry
      shell: bash
      run: cargo login --registry ${{ inputs.name }} ${{ inputs.token }}

    - name: Login to azure for orica cosmos private registry
      if: inputs.cos_username != '' && inputs.cos_password != '' && inputs.cos_tenant != '' && inputs.cos_subscription != ''
      uses: azure/login@v2
      with:
        creds: '{"clientId": "${{ inputs.cos_username }}", "clientSecret": "${{ inputs.cos_password }}", "tenantId": "${{ inputs.cos_tenant }}", "subscriptionId": "${{ inputs.cos_subscription }}"}'
    - name: Login to orica cosmos private registry
      uses: azure/cli@v2
      if: inputs.cos_username != '' && inputs.cos_password != '' && inputs.cos_tenant != '' && inputs.cos_subscription != ''
      with:
        inlineScript: |
          az account get-access-token --query "join(' ', ['Bearer', accessToken])" --output tsv | cargo login --registry cos
    - name: Login to our private npm registry
      uses: actions/setup-node@v4
      with:
        check-latest: true
        registry-url: https://npm.pkg.github.com/
        scope: "@${{ github.repository_owner }}"
