name: "Login to private Cargo Registry"
description: "Composite action to login to a private Cargo Registry"

inputs:
  private_key:
    required: false
    default: ""
    description: "Private Key to use for the registry index"
  host:
    required: true
    description: "Registry host for keyscan"
  name:
    required: true
    description: "Name to use for the registry login"
  token:
    required: true
    description: "Token to use for the registry login"
runs:
  using: "composite"
  steps:
    - name: Access private registry
      uses: webfactory/ssh-agent@v0.5.4
      if: ${{ inputs.private_key != ''}}
      with:
        ssh-private-key: ${{ inputs.private_key }}
    - name: Keyscan
      shell: bash
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa ${{ inputs.host }} >> ~/.ssh/known_hosts
    - name: Login to private registry
      shell: bash
      run: cargo login --registry ${{ inputs.name }} ${{ inputs.token }}
    - name: Add HTTP-AGent to Cargo
      shell: bash
      run: |
        touch ~/.cargo/config.toml 
        grep -qxF '[http]' ~/.cargo/config.toml || echo "[http]" >> ~/.cargo/config.toml
        grep -qxF 'user-agent = "shipyard ${{ inputs.token }}"' ~/.cargo/config.toml || echo 'user-agent = "shipyard ${{ inputs.token }}"' >> ~/.cargo/config.toml
