name: "Login to private Cargo Registry"
description: "Composite action to login to a private Cargo Registry"

inputs:
  private_key:
    required: false
    default: ""
    description: "Private Key to use for the registry index"
  host:
    required: true
    description: "Registry host for keyscan"
  name:
    required: true
    description: "Name to use for the registry login"
  token:
    required: true
    description: "Token to use for the registry login"
  additional_private_keys:
    default: ""
    description: "Additional private keys to add to the ssh-agent"
runs:
  using: "composite"
  steps:
    - name: Access private registry
      uses: webfactory/ssh-agent@v0.5.4
      if: ${{ inputs.private_key != '' || inputs.additional_private_keys != '' }}
      with:
        ssh-private-key: |
          ${{ inputs.private_key }}
          ${{ inputs.additional_private_keys }}
    - name: Use ssh for github dep
      shell: bash
      run: |
        echo '[url "ssh://git@github.com/ForesightMiningSoftwareCorporation/"]' >> $HOME/.gitconfig
        echo "  insteadOf = https://github.com/ForesightMiningSoftwareCorporation/" >> $HOME/.gitconfig
        echo '[url "ssh://git@github.com/foresightminingsoftwarecorporation"]' >> $HOME/.gitconfig
        echo "  insteadOf = https://github.com/foresightminingsoftwarecorporation" >> $HOME/.gitconfig
    - name: Keyscan
      shell: bash
      run: |
        mkdir -p $HOME/.ssh
        ssh-keyscan -t rsa ${{ inputs.host }} >> $HOME/.ssh/known_hosts
    - name: Login to private registry
      shell: bash
      run: cargo login --registry ${{ inputs.name }} ${{ inputs.token }}