name: "Check if rust public crate exists"
description: "Composite action to check if a cargo crate exists"

inputs:
  working-directory:
    required: true
    description: "The working directory"
outputs:
  exists:
    value: ${{ steps.check.outputs.PACKAGE_EXISTS }}
    description: "Does the package exists"

runs:
  using: "composite"
  steps:
    - name: Configure Git to use global ignore file
      shell: bash
      run: git config --global core.excludesfile ~/.gitignore_global
    - name: "Ensure we don't track the new resources in git"
      shell: bash
      run: |
        echo ".github_wide_resources/" >> ~/.gitignore_global
        echo "PACKAGE_EXISTS" >> ~/.gitignore_global
    - name: Checkout github wide resources
      uses: actions/checkout@v3
      with:
        ref: "v1"
        repository: ForesightMiningSoftwareCorporation/github
        path: ".github_wide_resources"
    - name: Install Updatecli in the runner
      uses: updatecli/updatecli-action@v2
      with:
        version: "v0.44.0"
    - name: Run UpdateCli with Cargo check package
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      id: check
      run: |
        rm PACKAGE_EXISTS || true
        updatecli apply --config $GITHUB_WORKSPACE/.github_wide_resources/updatecli/updatecli.d/rust/check-public-crate-exists.yml --values $GITHUB_WORKSPACE/.github_wide_resources/updatecli/values.github-action.yaml || true
        PACKAGE_EXISTS=$(cat PACKAGE_EXISTS 2>/dev/null || echo "true")
        echo "PACKAGE_EXISTS=$PACKAGE_EXISTS" >> $GITHUB_OUTPUT
