[licenses]
version = 2
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Artistic-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "MPL-2.0",
    "0BSD",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
    "OFL-1.1",
    "LicenseRef-UFL-1.0",
]
unused-allowed-license = "allow"
[licenses.private]
ignore = true
[sources]
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
    "ssh://git@ssh.shipyard.rs/foresight-mining-software-corporation/crate-index.git"
]
[bans]
multiple-versions = "deny"
skip = [
   { name = "toml" },
   { name = "self_cell" },
   { name = "memoffset" },
   { name = "dirs-next" },
   { name = "async-fs" },
   { name = "async-io" },
   { name = "serde_with" },
   { name = "serde_with_macros" },
   { name = "vector-expr" },
   { name = "num" },
   { name = "num-rational" },
   { name = "num-complex" },
   { name = "num-bigint" },
   { name = "itertools" },
   { name = "glam" },
   { name = "strum" },
   { name = "strum_macros" },
   { name = "uom" },
   { name = "ordered-float" },
   { name = "pem" },
   { name = "nix" },
   { name = "robust" },
   { name = "polling" },
   { name = "miniz_oxide" },
   # Doesn't seem to cause problems but is fsl internal
   { name = "dag_tables" },
   { name = "bevy_mod_raycast" },
]
skip-tree = [
    { name = "bevy" },
    { name = "azure_core" },
    { name = "azure_storage" },
    { name = "azure_storage_blobs" },
]   
