name: "Check if cargo crate exists"
description: "Composite action to check if a cargo crate exists"

inputs:
  working-directory:
    required: true
    description: "The working directory"
  cargo_private_registry_git_http_url:
    description: "Cargo Registry git url"
    required: true
  cargo_private_registry_git_http_username:
    description: "Cargo Registry git username"
    required: true
  cargo_private_registry_git_http_password:
    description: "Cargo Registry git password"
    required: true
outputs:
  exists:
    value: ${{ steps.check.outputs.PACKAGE_EXISTS }}
    description: "Does the package exists"

runs:
  using: "composite"
  steps:
    - name: Configure Git to use global ignore file
      shell: bash
      run: git config --global core.excludesfile ~/.gitignore_global
    - name: "Ensure we don't track the new resources in git"
      shell: bash
      run: |
        echo ".github_wide_resources/" >> ~/.gitignore_global
        echo "PACKAGE_EXISTS" >> ~/.gitignore_global
    - name: Checkout github wide resources
      uses: actions/checkout@v3
      with:
        ref: "v1"
        repository: ForesightMiningSoftwareCorporation/github
        path: ".github_wide_resources"
    - name: Install Updatecli in the runner
      uses: updatecli/updatecli-action@v2
    - name: Run UpdateCli with Cargo check package
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      id: check
      run: |
        updatecli apply --config $GITHUB_WORKSPACE/.github_wide_resources/updatecli/updatecli.d/rust/check-crate-exists.yml --values $GITHUB_WORKSPACE/.github_wide_resources/updatecli/values.github-action.yaml || true
        PACKAGE_EXISTS=$(cat PACKAGE_EXISTS 2>/dev/null || echo "false")
        echo "PACKAGE_EXISTS=$PACKAGE_EXISTS" >> $GITHUB_OUTPUT
      env:
        UPDATECLI_CARGO_PRIVATE_REGISTRY_GIT_HTTP_URL: ${{ inputs.cargo_private_registry_git_http_url }}
        UPDATECLI_CARGO_PRIVATE_REGISTRY_GIT_HTTP_USERNAME: ${{ inputs.cargo_private_registry_git_http_username }}
        UPDATECLI_CARGO_PRIVATE_REGISTRY_GIT_HTTP_PASSWORD: ${{ inputs.cargo_private_registry_git_http_password }}
