name: "Run shell script and get the stdout and stderr as outputs"
description: "Composite action to run shell script with stdout"

inputs:
  command:
    required: true
    description: "The command"
  id:
    required: true
    description: "The id for the step artifacts"
  working-directory:
    required: true
    description: "The working directory"
  loki_url:
    required: true
    description: 'URL to contact loki'
  loki_org_id:
    required: true
    description: 'Loki Org Id'
  loki_username:
    required: true
    description: 'Username to talk to loki'
  loki_password:
    required: true
    description: 'Password to talk to loki'
outputs:
  stdout:
    description: "Command STDOUT"
    value: ${{ steps.command.outputs.stdout }}
  stderr:
    description: "Command STDERR"
    value: ${{ steps.command.outputs.stderr }}
  exitcode:
    description: "Command exitcode"
    value: ${{ steps.command.outputs.exitcode }}
runs:
  using: "composite"
  steps:
    - name: Run Command
      shell: bash
      id: command
      continue-on-error: true
      working-directory: ${{ inputs.working-directory }}
      run: |
        if ${{ inputs.command }} 2>&1 | ts "%Y-%m-%dT%H:%M:%.SZ; " > output.txt; then
          rc=0
        else
          rc=$?
        fi
        echo "exitcode=$rc" >> $GITHUB_OUTPUT
    - name: Upload stdout
      uses: ForesightMiningSoftwareCorporation/upload-log-to-loki@releases/v1
      with:
        log_file: ${{ inputs.working-directory }}/output.txt
        loki_url: ${{ inputs.loki_url }}
        loki_username: ${{ inputs.loki_username }}
        loki_password: ${{ inputs.loki_password }}
        loki_org_id: ${{ inputs.loki_org_id }}
        loki_labels: 'job=${{ github.job }},workflow=${{ github.workflow }},action=${{ github.action }},id=${{ inputs.id }}'
    - name: Check exit code
      shell: bash
      run: |
        echo "Command exited with code ${{ steps.command.outputs.exitcode }}"
        exit ${{ steps.command.outputs.exitcode }}