name: "Run shell script and get the stdout and stderr as outputs"
description: "Composite action to run shell script with stdout"

inputs:
  command:
    required: true
    description: "The command"
  working_directory:
    required: true
    description: "The working directory"
outputs:
  stdout:
    description: "Command STDOUT"
    value: ${{ steps.command.outputs.stdout }}
  stderr:
    description: "Command STDERR"
    value: ${{ steps.command.outputs.stderr }}
  exitcode:
    description: "Command exitcode"
    value: ${{ steps.command.outputs.exitcode }}
runs:
  using: "composite"
  steps:
    - name: Run Command
      shell: bash
      id: command
      continue-on-error: true
      working-directory: ${{ inputs.working_directory }}
      run: |
        if ${{ inputs.command }} 2>&1 | ts "%Y-%m-%dT%H:%M:%.SZ; " | tee output.txt; then
          rc=0
        else
          rc=$?
        fi
        echo "exitcode=$rc" >> $GITHUB_OUTPUT
    - name: Check exit code
      shell: bash
      run: |
        echo "Command exited with code ${{ steps.command.outputs.exitcode }}"
        exit ${{ steps.command.outputs.exitcode }}
