name: "Login to public Cargo Registry"
description: "Composite action to login to the public Cargo Registry"

inputs:
  token:
    required: true
    description: "Token to use for the registry login"
runs:
  using: "composite"
  steps:
    - name: Login to public registry
      shell: bash
      run: cargo login ${{ inputs.token }}