name: Build builder for orica_server with tagged version

on:
  workflow_dispatch:

jobs:
  build-rust-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Build and Push Image with Cache
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: docker/orica_server_builder
          file: Dockerfile_versioned
          push: true
          build-args: |
            RUST_VERSION=1.80
          tags: |
            ghcr.io/foresightminingsoftwarecorporation/orica-server-builder-versioned:rust-1.80
