name: Build builder for axum_server related servers
on:
  workflow_dispatch:
    inputs:
      rust_version:
        type: string
        default: "1.82"
        description: Rust rust_version to install

jobs:
  build-rust-test-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: docker/axum_server_builder
          file: docker/axum_server_builder/Dockerfile
          push: true
          build-args: |
            RUST_VERSION=${{ inputs.rust_version }}
          tags: |
            ghcr.io/foresightminingsoftwarecorporation/axum-server-builder:${{ inputs.rust_version }}
