name: Build ci image

on:
  workflow_dispatch:
    inputs:
      rust_version:
        description: "Rust version to install"
        default: "1.77"
        type: string
      github_runner_version:
        description: "Github Runner Version"
        default: "latest"
        type: string
      context:
        type: string
        default: https://github.com/ForesightMiningSoftwareCorporation/github.git#v2:docker/ci
      additional_tag:
        description: "Additional tag for docker building"
        type: string

jobs:
  build-rust-test-image:
    runs-on: ubuntu-latest
    if: ${{ inputs.rust_version != 'none' }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Build and Push Image with Cache
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          push: true
          build-args: |
            RUST_VERSION=${{ inputs.rust_version }}
            GITHUB_RUNNER_VERSION=${{ inputs.github_runner_version }}
          tags: |
            ghcr.io/foresightminingsoftwarecorporation/ci:latest
            ${{ inputs.additional_tag && format('ghcr.io/foresightminingsoftwarecorporation/ci:{0}', inputs.additional_tag) || '' }}
            ${{ format('ghcr.io/foresightminingsoftwarecorporation/ci:{0}', inputs.rust_version) }}
