name: Build builder for orica_blast_physics

on:
  workflow_dispatch:

jobs:
  build-orica-blast-physics-builder-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Build and Push Image with Cache
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: docker/blast_physics_builder
          push: true
          tags: |
            ghcr.io/foresightminingsoftwarecorporation/orica-blast-physic-builder:latest