on:
  workflow_call:
    inputs:
      check_changed_outcome:
        type: string
        default: "success"
        description: "Result of the check workspace command"
      run_type:
        type: string
        default: "checks"
        description: "Type of run (`checks` or `publishing`)"
      fslabscli_version:
        type: string
        description: "Fslabscli version"
jobs:
  results:
    name: ${{ inputs.run_type }} summaries
    runs-on: ubuntu-latest
    steps:
      - id: generate_token
        name: Generate token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.FMSC_BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.FMSC_BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Install FSLABScli
        uses: ForesightMiningSoftwareCorporation/fslabscli-action@v1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          version: ${{ inputs.fslabscli_version }}
      - uses: actions/download-artifact@v4
        id: download
        with:
          pattern: fslabs__${{ inputs.run_type }}__${{ github.run_id }}__${{ github.run_attempt }}__*
          merge-multiple: true

      - name: Generate Job Output
        shell: bash
        run: |
          fslabscli summaries \
            -w ${{ steps.download.outputs.download-path }} \
            --run-type=${{ inputs.run_type }} \
            --output $GITHUB_STEP_SUMMARY \
            --github-token=${{ steps.generate_token.outputs.token }} \
            --github-event-name=${{ github.event_name }} \
            --github-issue-number=${{ github.event.number || 0 }} \
            --github-repo=${{ github.repository }} \
            --check-changed-outcome=${{ inputs.check_changed_outcome }} \
            --hide-previous-pr-comment
