name: Validate Pull requests use conventional commit

on:
  pull_request:
    branches: [master, main]

jobs:
  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v2.0.0
        with:
          pr-body-regex: ""
