on:
  workflow_call:
    outputs:
      released:
        description: Was the crate released
        value: "true"
    inputs:
      package:
        description: Name of the package
        type: string
      version:
        description: Version of the package
        type: string
      working_directory:
        type: string
        description: "Binary to build"
        default: "."
      toolchain:
        type: string
        description: "Rust toolchain to use"
        default: "stable"
      context:
        type: string
        description: "Path to docker context"
        default: "default-docker-context-replace-me"
      dockerfile:
        type: string
        description: "The path to the Dockerfile to use"
        default: Dockerfile
      image:
        type: string
        required: true
        description: "Docker image name"
      registry:
        type: string
        default: "oreprohub.azurecr.io"
        description: "Docker registry"
      package_detail:
        type: string
        default: "{}"
        description: "Json encoded string of the package detail as computed by fslabscli"

jobs:
  docker_publish:
    runs-on: rust-1-76-scale-set
    steps:
      - name: Set start time as env variable
        id: start_time
        run: echo "value=$(date +'%s')000" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v4

      - uses: SebRollen/toml-action@v1.0.2
        id: read_version
        with:
          file: "${{ inputs.working_directory }}/Cargo.toml"
          field: "package.version"
      #
      # Login to registry (ACR)
      - name: Login to oreprohub
        uses: docker/login-action@v3
        if: ${{ inputs.registry == 'oreprohub.azurecr.io' }}
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          logout: false

      - name: Login to oricacrplatformfslabs001
        uses: docker/login-action@v3
        with:
          registry: oricacrplatformfslabs001.azurecr.io
          username: ${{ secrets.DOCKER_ORICACRPLATFORMFSLABS001_AZURECR_IO_USERNAME }}
          password: ${{ secrets.DOCKER_ORICACRPLATFORMFSLABS001_AZURECR_IO_PASSWORD }}
          logout: false

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}

      - uses: ForesightMiningSoftwareCorporation/github/.github/actions/login-private-registry@v2
        with:
          private_key: ${{ secrets.CARGO_PRIVATE_REGISTRY_SSH_PRIVATE_KEY }}
          host: ${{ secrets.CARGO_PRIVATE_REGISTRY_HOST }}
          name: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}
          additional_private_keys: |
            ${{ secrets.OREPROLIB_SSH_PRIVATE_KEY }}
            ${{ secrets.SPARKL_BLAST_SSH_PRIVATE_KEY }}
            ${{ secrets.OREPRO_API_CLIENT_SSH_KEY }}
            ${{ secrets.OREPRO_ESLINT_CONFIG_SSH_KEY }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Use user-agent for private registry
        shell: bash
        run: |
          echo "\"shipyard ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN  }}\"" > ./shipyard_token

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context == 'default-docker-context-replace-me' && inputs.working_directory || inputs.context }}
          push: true
          file: "${{ inputs.working_directory }}/${{ inputs.dockerfile }}"
          ssh: default=${{ env.SSH_AUTH_SOCK }}
          secrets: |
            node_auth_token="${{ secrets.GITHUB_TOKEN }}"
            cargo_http_user_agent="shipyard ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN  }}"
            cargo_private_registry_token="${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN  }}"
            cargo_private_registry_name="${{ secrets.CARGO_PRIVATE_REGISTRY_NAME  }}"
          tags: |
            ${{ inputs.registry }}/${{ inputs.image }}:${{ steps.read_version.outputs.value }}
            ${{ inputs.registry }}/${{ inputs.image }}:latest
          #cache-from: type=gha
          #cache-to: type=gha,mode=max

      - name: Write outputs to file
        shell: bash
        if: always()
        working-directory: ${{ runner.temp }}
        run: |
          tee -a ${{ inputs.package }}-docker-publish.json <<EOF
          {
            "name": "${{ inputs.package }}",
            "start_time": "${{ steps.start_time.outputs.value }}",
            "end_time": "$(date +'%s')000",
            "working_directory": "${{ inputs.working_directory }}",
            "type": docker-publish",
            "server_url": "${{ github.server_url }}",
            "repository": "${{ github.repository }}",
            "run_id": "${{ github.run_id }}",
            "run_attempt": "${{ github.run_attempt }}",
            "actor": "${{ github.actor }}",
            "event_name": "${{ github.event_name }}",
            "outputs": {
              "released": true,
              "version": "${{ inputs.version }}"
            }
          }
          EOF
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fslabs__publishing__${{ github.run_id }}__${{ github.run_attempt }}__${{ inputs.package }}-docker-publish
          path: ${{ runner.temp }}/${{ inputs.package }}-docker-publish.json
