on:
  workflow_call:
    outputs:
      released:
        description: Was the crate released
        value: ${{ jobs.docker_publish.outputs.released }}
    inputs:
      working-directory:
        type: string
        description: "Binary to build"
        default: "."
      dockerfile:
        type: string
        description: "The path to the Dockerfile to use"
        default: Dockerfile
      image:
        type: string
        required: true
        description: "Docker image name"
      registry:
        type: string
        default: "oreprohub.azurecr.io"
        description: "Docker registry"

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ fromJSON(steps.check_version_exists.outputs.exists) == false && 'true' || 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: SebRollen/toml-action@v1.0.2
        id: read_version
        with:
          file: '${{ inputs.working-directory }}/Cargo.toml'
          field: 'package.version'

      # Login to registry (ACR)
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.registry == 'oreprohub.azurecr.io' && secrets.ACR_USERNAME || github.actor }}
          password: ${{ inputs.registry == 'oreprohub.azurecr.io' && secrets.ACR_PASSWORD || secrets.GITHUB_TOKEN }}

      - name: Check Docker version exists
        id: check_version_exists
        uses: foresightminingsoftwarecorporation/docker-check-exists@v1
        with:
          repository: ${{ inputs.registry }}
          username: ${{ inputs.registry == 'oreprohub.azurecr.io' && secrets.ACR_USERNAME || github.actor }}
          password: ${{ inputs.registry == 'oreprohub.azurecr.io' && secrets.ACR_PASSWORD || secrets.GITHUB_TOKEN }}
          image_name: ${{ inputs.image }}
          version: ${{ steps.read_version.outputs.value }}

      - uses: dtolnay/rust-toolchain@master
        if: ${{ fromJSON(steps.check_version_exists.outputs.exists) == false }}
        with:
          toolchain: 1.69

      - uses: ForesightMiningSoftwareCorporation/github/.github/actions/login-private-registry@v1.1.0
        if: ${{ fromJSON(steps.check_version_exists.outputs.exists) == false }}
        with:
          private_key: ${{ secrets.CARGO_PRIVATE_REGISTRY_SSH_PRIVATE_KEY }}
          host: ${{ secrets.CARGO_PRIVATE_REGISTRY_HOST }}
          name: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}
          additional_private_keys: |
            ${{ secrets.OREPROLIB_SSH_PRIVATE_KEY }}

      - name: Set up Docker Buildx
        if: ${{ fromJSON(steps.check_version_exists.outputs.exists) == false }}
        uses: docker/setup-buildx-action@v2

      - name: Use user-agent for private registry
        if: ${{ fromJSON(steps.check_version_exists.outputs.exists) == false }}
        shell: bash
        run: |
          echo "\"shipyard ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN  }}\"" > ./shipyard_token

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        if: ${{ fromJSON(steps.check_version_exists.outputs.exists) == false }}
        with:
          context: ${{ inputs.working-directory }}
          push: true
          file: "${{ inputs.working-directory }}/${{ inputs.dockerfile }}"
          ssh:
            default=${{ env.SSH_AUTH_SOCK }}
          secrets: |
            node_auth_token="${{ secrets.GITHUB_TOKEN }}"
            cargo_http_user_agent="shipyard ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN  }}"
            cargo_private_registry_token="${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN  }}"
            cargo_private_registry_name="${{ secrets.CARGO_PRIVATE_REGISTRY_NAME  }}"
          tags: |
            ${{ inputs.registry }}/${{ inputs.image }}:${{ steps.read_version.outputs.value }}
            ${{ inputs.registry }}/${{ inputs.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
