on:
  workflow_call:
    outputs:
      released:
        description: Was the crate released
        value: ${{ jobs.create_release_npm.outputs.released }}
    inputs:
      working_directory:
        type: string
        default: ""
        description: Subdirectory to treat as repo root
      toolchain:
        type: string
        default: "1.76"
        description: Rust toolchain to install
      with_napi:
        type: string
        default: "true"
        description: "Should napi be used to deploy bindings"
      package_detail:
        type: string
        default: "{}"
        description: "Json encoded string of the package detail as computed by fslabscli"

jobs:
  derive_info:
    name: Check NPM Packages
    runs-on: "ubuntu-latest"
    outputs:
      name: ${{ steps.read_package_json.outputs.name }}
      current-version: ${{ steps.read_package_json.outputs.current-version }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.working_directory }}/package.json
      - name: Get version in package.json
        id: read_package_json
        run: |
          echo "name=$(cat package.json | jq -r '.name' | rev | cut -d'/' -f 1 | rev)" >> $GITHUB_OUTPUT
          echo "current-version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.working_directory }}

  build_artifacts_rust:
    name: Build napi artifacts
    if: "${{inputs.with_napi == 'true'}}"
    needs:
      - derive_info
    strategy:
      matrix:
        os:
          - name: ubuntu-latest-16-cores
            arch: x86_64-unknown-linux-musl
            ext: ""
            docker_image: ghcr.io/foresightminingsoftwarecorporation/napi-rs-docker-builder:main
            additional_packages: ""
          - name: ubuntu-latest-16-cores
            arch: x86_64-unknown-linux-gnu
            ext: ""
            docker_image: ""
            additional_packages: "librust-atk-dev libgtk-3-dev libglib2.0-dev"
          - name: windows-latest-16-cores-custom
            arch: x86_64-pc-windows-msvc
            ext: .exe
            docker_image: ""
            additional_packages: ""
          - name: macos-latest-xlarge
            arch: aarch64-apple-darwin
            docker_image: ""
            additional_packages: ""
    runs-on: ${{ matrix.os.name }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - uses: ForesightMiningSoftwareCorporation/github/.github/actions/login-private-registry@v2
        with:
          private_key: ${{ secrets.CARGO_PRIVATE_REGISTRY_SSH_PRIVATE_KEY }}
          host: ${{ secrets.CARGO_PRIVATE_REGISTRY_HOST }}
          name: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}

      - name: Build rust package
        uses: ForesightMiningSoftwareCorporation/github/.github/actions/build-napi-artifact@v2
        with:
          runner_os: ${{ matrix.os.name }}
          runner_arch: ${{ matrix.os.arch }}
          runner_extension: ${{ matrix.os.ext }}
          docker_image: ${{ matrix.os.docker_image }}
          node_auth_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.GH_REGISTRY_PACKAGES }}
          shipyard: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          shipyard_token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}
          working_directory: ${{ inputs.working_directory }}
          bin: ${{ needs.derive_info.outputs.name }}
          version: ${{ needs.derive_info.outputs.current_version }}
          additional_packages: ${{ matrix.os.additional_packages }}

  create_release_npm:
    name: Publish NPM Packages
    runs-on: "ubuntu-latest"
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    outputs:
      released: ${{ steps.publish.outputs.released }}
    needs:
      - derive_info
      - build_artifacts_rust
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ inputs.working_directory }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.working_directory }}/raw_artifacts

      - name: Move Artifacts and rename
        shell: bash
        run: |-
          mkdir -p artifacts
          for f in raw_artifacts/bindings-${{ needs.derive_info.outputs.name }}-*; do
              NEW_NAME="${f/-${{ needs.derive_info.outputs.name }}/}"
              mv -- "$f" "${NEW_NAME/raw_artifacts/artifacts}"
          done
        working-directory: ${{ inputs.working_directory }}

      - name: Move artifacts
        run: yarn artifacts
        working-directory: ${{ inputs.working_directory }}

      - uses: ForesightMiningSoftwareCorporation/github/.github/actions/login-private-registry@v2
        with:
          private_key: ${{ secrets.CARGO_PRIVATE_REGISTRY_SSH_PRIVATE_KEY }}
          host: ${{ secrets.CARGO_PRIVATE_REGISTRY_HOST }}
          name: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}

      - name: Publish
        id: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_REGISTRY_PACKAGES }}
        run: |
          if npm publish ; then
            released=true
          else
            rc=false
          fi
          echo "released=$released" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.working_directory }}
