on:
  workflow_call:
    outputs:
      released:
        description: Was the crate released
        value: "true"
    inputs:
      working_directory:
        type: string
        default: ""
        description: Subdirectory to treat as repo root
      toolchain:
        type: string
        default: "1.73"
        description: Rust toolchain to install

jobs:
  build_artifacts_rust:
    name: Build napi artifacts
    strategy:
      matrix:
        os:
          - name: ubuntu-latest-16-cores
            arch: x86_64-unknown-linux-gnu
            ext: ""
          - name: ubuntu-latest-16-cores
            arch: x86_64-unknown-linux-gnu
            ext: ""
          - name: windows-latest-16-cores-custom
            arch: x86_64-pc-windows-msvc
            ext: .exe
          - name: macos-latest-xlarge
            arch: aarch64-apple-darwin
    runs-on: ${{ matrix.os.name }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - uses: ForesightMiningSoftwareCorporation/github/.github/actions/login-private-registry@v1
        with:
          private_key: ${{ secrets.CARGO_PRIVATE_REGISTRY_SSH_PRIVATE_KEY }}
          host: ${{ secrets.CARGO_PRIVATE_REGISTRY_HOST }}
          name: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}

      - name: Build rust package
        uses: ForesightMiningSoftwareCorporation/github/.github/actions/build-napi-artifact@v1
        with:
          runner_os: ${{ matrix.os.name }}
          runner_arch: ${{ matrix.os.arch }}
          runner_extension: ${{ matrix.os.ext }}
          docker: ghcr.io/foresightminingsoftwarecorporation/napi-rs-docker-builder:latest
          docker_build: yarn install && yarn build --target x86_64-unknown-linux-musl --js=false
          node_auth_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.GH_REGISTRY_PACKAGES }}
          shipyard: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          shipyard_token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}
          working-directory: ${{ inputs.working_directory }}
          bin: ${{ needs.check_release_npm.outputs.name }}
          version: ${{ needs.check_release_npm.outputs.current_version }}

  create_release_npm:
    name: Publish NPM Packages
    runs-on: "ubuntu-latest"
    needs:
      - build_artifacts_rust
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ inputs.working_directory }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.working_directory }}/raw_artifacts

      - name: Move Artifacts and rename
        shell: bash
        run: |-
          mkdir -p artifacts
          for f in raw_artifacts/bindings-${{ needs.check_release_npm.outputs.name }}-*; do
              NEW_NAME="${f/-${{ needs.check_release_npm.outputs.name }}/}"
              mv -- "$f" "${NEW_NAME/raw_artifacts/artifacts}"
          done
        working-directory: ${{ inputs.working_directory }}

      - name: Move artifacts
        run: yarn artifacts
        working-directory: ${{ inputs.working_directory }}

      - uses: ForesightMiningSoftwareCorporation/github/.github/actions/login-private-registry@v1
        with:
          private_key: ${{ secrets.CARGO_PRIVATE_REGISTRY_SSH_PRIVATE_KEY }}
          host: ${{ secrets.CARGO_PRIVATE_REGISTRY_HOST }}
          name: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}

      - name: Publish
        id: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_REGISTRY_PACKAGES }}
        if: ${{ needs.check_release_npm.outputs.exists == 'false' }}
        run: |
          if npm publish ; then
            released=true
          else
            rc=false
          fi
          echo "released=$released" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.working_directory }}
