on:
  workflow_call:
    outputs:
      released:
        description: Was the crate released
        value: ${{ jobs.create_release_npm.outputs.released }}
    inputs:
      package:
        description: Name of the package
        type: string
      version:
        description: Version of the package
        type: string
      working_directory:
        type: string
        default: ""
        description: Subdirectory to treat as repo root

jobs:
  derive_info:
    name: Check NPM Packages
    runs-on: "ubuntu-latest"
    outputs:
      name: ${{ steps.read_package_json.outputs.name }}
      current-version: ${{ steps.read_package_json.outputs.current-version }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.working_directory }}/package.json
      - name: Get version in package.json
        id: read_package_json
        run: |
          echo "name=$(cat package.json | jq -r '.name' | rev | cut -d'/' -f 1 | rev)" >> $GITHUB_OUTPUT
          echo "current-version=$(cat package.json | jq -r '.version')" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.working_directory }}

  build_artifacts_rust:
    name: Build napi artifacts
    needs:
      - derive_info
    strategy:
      matrix:
        os:
          - name: ubuntu-latest-16-cores
            arch: x86_64-unknown-linux-musl
            ext: ""
            docker_image: ghcr.io/foresightminingsoftwarecorporation/napi-rs-docker-builder:latest
            additional_packages: ""
          - name: ubuntu-latest-16-cores
            arch: x86_64-unknown-linux-gnu
            ext: ""
            docker_image: ""
            additional_packages: "librust-atk-dev libgtk-3-dev libglib2.0-dev libasound2-dev libudev-dev"
          - name: windows-latest-16-cores-custom
            arch: x86_64-pc-windows-msvc
            ext: .exe
            docker_image: ""
            additional_packages: ""
          - name: macos-latest-xlarge
            arch: aarch64-apple-darwin
            docker_image: ""
            additional_packages: ""
    runs-on: ${{ matrix.os.name }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - uses: ForesightMiningSoftwareCorporation/github/.github/actions/login-private-registry@v3.2.0
        with:
          private_key: ${{ secrets.CARGO_PRIVATE_REGISTRY_SSH_PRIVATE_KEY }}
          host: ${{ secrets.CARGO_PRIVATE_REGISTRY_HOST }}
          name: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}
          cos_username: ${{ secrets.CARGO_COS_PRIVATE_REGISTRY_USERNAME }}
          cos_password: ${{ secrets.CARGO_COS_PRIVATE_REGISTRY_PASSWORD }}
          cos_tenant: ${{ secrets.CARGO_COS_PRIVATE_REGISTRY_TENANT }}
          cos_subscription: ${{ secrets.CARGO_COS_PRIVATE_REGISTRY_SUBSCRIPTION }}

      - name: Build rust package
        uses: ForesightMiningSoftwareCorporation/github/.github/actions/build-napi-artifact@v3.0.0
        with:
          runner_os: ${{ matrix.os.name }}
          runner_arch: ${{ matrix.os.arch }}
          runner_extension: ${{ matrix.os.ext }}
          docker_image: ${{ matrix.os.docker_image }}
          node_auth_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.GH_REGISTRY_PACKAGES }}
          shipyard: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          shipyard_token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}
          working_directory: ${{ inputs.working_directory }}
          bin: ${{ needs.derive_info.outputs.name }}
          version: ${{ needs.derive_info.outputs.current_version }}
          additional_packages: ${{ matrix.os.additional_packages }}

  create_release_npm:
    name: Publish NPM Packages
    runs-on: "ubuntu-latest"
    if: ${{ !cancelled() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    outputs:
      released: ${{ steps.publish.outputs.released }}
    needs:
      - derive_info
      - build_artifacts_rust
    steps:
      - name: Set start time as env variable
        id: start_time
        run: echo "value=$(date +'%s')000" >> $GITHUB_OUTPUT
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ inputs.working_directory }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.working_directory }}/raw_artifacts

      - name: Move Artifacts and rename
        shell: bash
        run: |-
          mkdir -p artifacts
          for f in raw_artifacts/bindings-${{ needs.derive_info.outputs.name }}-*; do
              NEW_NAME="${f/-${{ needs.derive_info.outputs.name }}/}"
              mv -- "$f" "${NEW_NAME/raw_artifacts/artifacts}"
          done
        working-directory: ${{ inputs.working_directory }}

      - name: Move artifacts
        run: yarn artifacts
        working-directory: ${{ inputs.working_directory }}

      - uses: ForesightMiningSoftwareCorporation/github/.github/actions/login-private-registry@v3.2.0
        with:
          private_key: ${{ secrets.CARGO_PRIVATE_REGISTRY_SSH_PRIVATE_KEY }}
          host: ${{ secrets.CARGO_PRIVATE_REGISTRY_HOST }}
          name: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}
          cos_username: ${{ secrets.CARGO_COS_PRIVATE_REGISTRY_USERNAME }}
          cos_password: ${{ secrets.CARGO_COS_PRIVATE_REGISTRY_PASSWORD }}
          cos_tenant: ${{ secrets.CARGO_COS_PRIVATE_REGISTRY_TENANT }}

      - name: Publish
        id: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_REGISTRY_PACKAGES }}
        run: |
          if npm publish ; then
            released=true
          else
            rc=false
          fi
          echo "released=$released" >> $GITHUB_OUTPUT
        working-directory: ${{ inputs.working_directory }}

      - name: Write outputs to file
        shell: bash
        if: always()
        working-directory: ${{ runner.temp }}
        run: |
          tee -a ${{ inputs.package }}-npm-napi-publish.json <<EOF
          {
            "name": "${{ inputs.package }}",
            "start_time": "${{ steps.start_time.outputs.value }}",
            "end_time": "$(date +'%s')000",
            "working_directory": "${{ inputs.working_directory }}",
            "type": npm-napi-publish",
            "server_url": "${{ github.server_url }}",
            "repository": "${{ github.repository }}",
            "run_id": "${{ github.run_id }}",
            "run_attempt": "${{ github.run_attempt }}",
            "actor": "${{ github.actor }}",
            "event_name": "${{ github.event_name }}",
            "outputs": {
              "released": ${{ steps.publish.outcome == 'success' && true || false }},
              "version": "${{ inputs.version }}",
              "sha": "${{ github.sha }}"
            }
          }
          EOF
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: fslabs__publishing__${{ github.run_id }}__${{ github.run_attempt }}__${{ inputs.package }}-npm-napi-publish
          path: ${{ runner.temp }}/${{ inputs.package }}-npm-napi-publish.json
