name: Publish Release to Private Registry

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to publish'
        type: string
        default: 'main'
      runner:
        type: string
        default: "ubuntu-latest"
      toolchain:
        type: string
        default: "1.65"
        description: Rust toolchain to install
      initial_event_name:
        type: string
        default: "push"
        description: Event that triggered the workflow
      private-registry-host:
        required: true
        type: string
      private-registry-name:
        required: true
        type: string
      skip-test:
        type: boolean
        default: false
        description: Skip the test step
    secrets:
      github-token:
        required: true
      github-private-keys:
        required: false
        description: Private keys that need to be added to the ssh-agent
      private-registry-private-key:
        required: false
      private-registry-token:
        required: true

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  test:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust-test.yml@v1.0.0
    if: ${{ inputs.skip-test == false }}
    with:
      runner: ${{ inputs.runner }}
      toolchain: ${{ inputs.toolchain }}
      initial_event_name: ${{ inputs.initial_event_name }}
      private-registry-host: ${{ inputs.private-registry-host }}
      private-registry-name: ${{ inputs.private-registry-name }}
    secrets:
      github-token: ${{ secrets.github-token }}
      github-private-keys: ${{ secrets.github-private-keys }}
      private-registry-private-key: ${{ secrets.private-registry-private-key }}
      private-registry-token: ${{ secrets.private-registry-token }}
  set_version:
    needs:
      - test
    if: |
      always() && 
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    name: Release new version to private registry
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
      - name: Set Version
        shell: bash
        run: |
          echo "Setting version to ${{ github.ref }}"
          export VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Update Cargo.toml
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: "Cargo.toml"
          key: "package.version"
          value: "${{ env.VERSION }}"
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: git add Cargo.toml && git commit -m "Set version to $VERSION"
      - uses: ForesightMiningSoftwareCorporation/github/.github/actions/login-private-registry@v1.0.0
        with:
          private_key: ${{ secrets.private-registry-private-key }}
          host: ${{ inputs.private-registry-host }}
          name: ${{ inputs.private-registry-name }}
          token: ${{ secrets.private-registry-token }}
      - name: Publish to private registry
        shell: bash
        run: cargo publish --registry ${{ inputs.private-registry-name }}
      - run: git push -u origin HEAD:${{ inputs.branch }}
