on:
  workflow_call:
    inputs:
      skip-test:
        type: string
        default: 'false'
        description: "Should the tests be ran"
      skip-test-publish:
        type: string
        default: 'false'
        description: "Should the publis dry-run test be ran"
      publish:
        type: string
        default: 'false'
        description: "Should the crate be published"
      publish_private_registry:
        type: string
        default: 'false'
        description: "Should the crate be published to the private registry"
      publish_public_registry:
        type: string
        default: 'false'
        description: "Should the crate be published to the public registry"
      publish_docker:
        type: string
        default: 'false'
        description: "Should the crate be published as a docker image"
      publish_binary:
        type: string
        default: 'false'
        description: "Should the crate be published as a binary"
      toolchain:
        type: string
        default: "1.65"
        description: Rust toolchain to install
      additional_script:
        type: string
        default: ""
        description: Additional script to run before the additional packages
      required_packages:
        type: string
        default: ""
        description: Package that needs to be installed before Rust compilation can happens
      working-directory:
        type: string
        default: "."
        description: Working directory to run the cargo command
      additional_args:
        type: string
        default: ""
        description: Additional arguments to pass to the cargo command
      custom_cargo_commands:
        type: string
        default: ""
        description: Cusom cargo commands that will be run after login
      dockerfile:
        type: string
        description: "The path to the Dockerfile to use"
        default: Dockerfile
      docker_image:
        type: string
        default: ''
        description: "Docker image name"
      binary_os_windows_enabled:
        type: string
        default: 'true'
        description: "Binary building: build on windows"
      binary_version_trigger:
        type: string
        default: 'patch'
        description: "Controls which update trigger a build"

jobs:
  test:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust-test.yml@v1.1.0
    if: ${{ inputs.skip-test != 'true' }}
    with:
      toolchain: ${{ inputs.toolchain }}
      additional_script: ${{ inputs.additional_script }}
      required_packages: ${{ inputs.required_packages }}
      working-directory: ${{ inputs.working-directory }}
      additional_args: ${{ inputs.additional_args }}
      custom_cargo_commands: ${{ inputs.custom_cargo_commands }}
      login_private_registry: ${{ inputs.publish_public_registry != 'true' }}
      skip-test-publish: ${{ inputs.skip-test-publish }}
    secrets: inherit
  publish_private_registry:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust_private_registry_publish.yml@v1.1.0
    if: always() && inputs.publish == 'true' && inputs.publish_private_registry == 'true' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs:
      - test
    with:
      toolchain: ${{ inputs.toolchain }}
      additional_script: ${{ inputs.additional_script }}
      required_packages: ${{ inputs.required_packages }}
      working-directory: ${{ inputs.working-directory }}
      additional_args: ${{ inputs.additional_args }}
      custom_cargo_commands: ${{ inputs.custom_cargo_commands }}
    secrets: inherit
  publish_public_registry:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust_public_registry_publish.yml@v1.1.0
    if: always() && inputs.publish == 'true' && inputs.publish_public_registry == 'true' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs:
      - test
    with:
      toolchain: ${{ inputs.toolchain }}
      additional_script: ${{ inputs.additional_script }}
      required_packages: ${{ inputs.required_packages }}
      working-directory: ${{ inputs.working-directory }}
      additional_args: ${{ inputs.additional_args }}
      custom_cargo_commands: ${{ inputs.custom_cargo_commands }}
    secrets: inherit
  publish_docker_registry:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/docker_publish.yml@v1.1.0
    if: always() && inputs.publish == 'true' && inputs.publish_docker == 'true' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs:
      - test
    with:
      working-directory: ${{ inputs.working-directory }}
      dockerfile: ${{ inputs.dockerfile }}
      image: ${{ inputs.docker_image }}
    secrets: inherit
  publish_binary:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust_binary_publish.yaml@binary_release
    needs:
      - test
    if: always() && inputs.publish == 'true' && inputs.publish_binary == 'true' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    with:
      toolchain: ${{ inputs.toolchain }}
      additional_script: ${{ inputs.additional_script }}
      required_packages: ${{ inputs.required_packages }}
      additional_args: ${{ inputs.additional_args }}
      custom_cargo_commands: ${{ inputs.custom_cargo_commands }}
      working-directory: ${{ inputs.working-directory }}
      os_windows_enabled: ${{ inputs.binary_os_windows_enabled }}
      version_trigger: ${{ inputs.binary_version_trigger }}
    secrets: inherit
  report_release:
    needs:
      - publish_private_registry
      - publish_public_registry
      - publish_docker_registry
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/gh-release-when-published.yaml@v1.1.0
    if: always() && inputs.publish && (needs.publish_private_registry.outputs.released == 'true' || needs.publish_public_registry.outputs.released == 'true' || needs.publish_docker_registry.outputs.released == 'true' || needs.publish_binary.outputs.released == 'true')
    with:
      working-directory: ${{ inputs.working-directory }}
      private_registry_release: ${{ inputs.publish_private_registry == 'true' }}
      public_registry_release: ${{ inputs.publish_public_registry == 'true' }}
      docker_release: ${{ inputs.publish_docker == 'true' }}
      binary_release: ${{ inputs.publish_binary == 'true' }}
    secrets: inherit
