on:
  workflow_call:
    inputs:
      skip-test:
        type: string
        default: 'false'
        description: "Should the tests be ran"
      skip-test-publish:
        type: string
        default: 'false'
        description: "Should the publis dry-run test be ran"
      publish:
        type: string
        default: 'false'
        description: "Should the crate be published"
      publish_private_registry:
        type: string
        default: 'false'
        description: "Should the crate be published to the private registry"
      publish_public_registry:
        type: string
        default: 'false'
        description: "Should the crate be published to the public registry"
      publish_docker:
        type: string
        default: 'false'
        description: "Should the docker image be built and published"
      toolchain:
        type: string
        default: "1.65"
        description: Rust toolchain to install
      additional_script:
        type: string
        default: ""
        description: Additional script to run before the additional packages
      required_packages:
        type: string
        default: ""
        description: Package that needs to be installed before Rust compilation can happens
      working-directory:
        type: string
        default: "."
        description: Working directory to run the cargo command
      additional_args:
        type: string
        default: ""
        description: Additional arguments to pass to the cargo command
      custom_cargo_commands:
        type: string
        default: ""
        description: Cusom cargo commands that will be run after login
      dockerfile:
        type: string
        description: "The path to the Dockerfile to use"
        default: Dockerfile
      docker_image:
        type: string
        default: ''
        description: "Docker image name"

jobs:
  test:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust-test.yml@v1.1.0
    if: ${{ inputs.skip-test != 'true' }}
    with:
      toolchain: ${{ inputs.toolchain }}
      additional_script: ${{ inputs.additional_script }}
      required_packages: ${{ inputs.required_packages }}
      working-directory: ${{ inputs.working-directory }}
      additional_args: ${{ inputs.additional_args }}
      custom_cargo_commands: ${{ inputs.custom_cargo_commands }}
      login_private_registry: ${{ inputs.publish_public_registry != 'true' }}
      skip-test-publish: ${{ inputs.skip-test-publish }}
    secrets: inherit
  publish_private_registry:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust_private_registry_publish.yml@v1.1.0
    if: always() && inputs.publish == 'true' && inputs.publish_private_registry == 'true' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs:
      - test
    with:
      toolchain: ${{ inputs.toolchain }}
      additional_script: ${{ inputs.additional_script }}
      required_packages: ${{ inputs.required_packages }}
      working-directory: ${{ inputs.working-directory }}
      additional_args: ${{ inputs.additional_args }}
      custom_cargo_commands: ${{ inputs.custom_cargo_commands }}
    secrets: inherit
  publish_public_registry:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust_public_registry_publish.yml@v1.1.0
    if: always() && inputs.publish == 'true' && inputs.publish_public_registry == 'true' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs:
      - test
    with:
      toolchain: ${{ inputs.toolchain }}
      additional_script: ${{ inputs.additional_script }}
      required_packages: ${{ inputs.required_packages }}
      working-directory: ${{ inputs.working-directory }}
      additional_args: ${{ inputs.additional_args }}
      custom_cargo_commands: ${{ inputs.custom_cargo_commands }}
    secrets: inherit
  publish_docker_registry:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/docker_publish.yml@v1.1.0
    if: always() && inputs.publish == 'true' && inputs.publish_docker == 'true' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs:
      - test
    with:
      working-directory: ${{ inputs.working-directory }}
      dockerfile: ${{ inputs.dockerfile }}
      image: ${{ inputs.docker_image }}
    secrets: inherit
