on:
  workflow_call:
    outputs:
      private_registry_released:
        description: Was it released to the private registry
        value: ${{ jobs.publish_private_registry.outputs.released }}
      public_registry_released:
        description: Was it released to the public registry
        value: ${{ jobs.publish_public_registry.outputs.released }}
      docker_released:
        description: Was it released to the docker registry
        value: ${{ jobs.publish_docker.outputs.released }}
      binary_released:
        description: Was it released as binary
        value: ${{ jobs.publish_binary.outputs.released }}
    inputs:
      skip-test:
        type: string
        default: "false"
        description: "Should the tests be run"
      skip-tests-no-changes:
        type: string
        default: "false"
        description: Skip tests when no changes were detected in any cargo workspace
      skip-miri-test:
        type: string
        default: "true"
        description: "Should miri tests be run"
      publish:
        type: string
        default: "false"
        description: "Should the crate be published"
      publish_private_registry:
        type: string
        default: "false"
        description: "Should the crate be published to the private registry"
      publish_public_registry:
        type: string
        default: "false"
        description: "Should the crate be published to the public registry"
      publish_docker:
        type: string
        default: "false"
        description: "Should the docker image be built and published"
      publish_binary:
        type: string
        default: "false"
        description: "Should the binary be built and published"
      toolchain:
        type: string
        default: "1.75"
        description:
          Rust toolchain to install.
          Do not set this to moving targets like "stable".
          Instead, leave it empty and regularly bump the default in this file.
      miri_toolchain:
        type: string
        default: "nightly-2023-08-02"
        description:
          Rust toolchain to use for Miri.
          Do not set this to moving targets like "nightly".
          Instead, leave it empty and regularly bump the default in this file.
      release_channel:
        type: string
        default: ""
        description: Hard coded release channel
      additional_cache_path:
        type: string
        default: ""
        description: Path of additional cache to get
      additional_cache_key:
        type: string
        default: ""
        description: Key of additional cache to get
      additional_cache_miss:
        type: string
        default: ""
        description: Script to run if additional cache miss
      additional_script:
        type: string
        default: ""
        description: Additional script to run before the additional packages
      required_packages:
        type: string
        default: ""
        description: Package that needs to be installed before Rust compilation can happens
      workspaces:
        type: string
        default: '[""]'
        description: JSON array of of Cargo workspaces
      working-directory:
        type: string
        default: "."
        description: Working directory to run the cargo command
      additional_args:
        type: string
        default: ""
        description: Additional arguments to pass to the cargo command
      custom_cargo_commands:
        type: string
        default: ""
        description: Cusom cargo commands that will be run after login
      docker-context:
        type: string
        description: "Path to docker context"
        default: "default-docker-context-replace-me"
      dockerfile:
        type: string
        description: "The path to the Dockerfile to use"
        default: Dockerfile
      docker_image:
        type: string
        default: ""
        description: "Docker image name"
      docker_registry:
        type: string
        default: "oreprohub.azurecr.io"
        description: "Docker registry"
      matrix_file:
        type: string
        default: ".github/workflows/matrix.json"
        description: "Matrix file to load"
      post_build_additional_script:
        type: string
        default: ""
        description: Post Build Additional script to run after the additional packages
      force_nonrequired_publish_test:
        type: string
        default: "false"
        description: Force the publish test to be marked as non required
      binary_sign_build:
        type: string
        default: "false"
        description: Should the binary bin be signed
      report_release:
        type: string
        default: "true"
        description: Should the release be reported

jobs:
  build_rust_ci_images:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/setup_rust_test_images.yaml@v1
    with:
      rust_versions: "${{ inputs.toolchain }} ${{ inputs.miri_toolchain }}"
    secrets: inherit
  test:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust-test.yml@v1
    if: ${{ inputs.skip-test != 'true' }}
    needs:
      - build_rust_ci_images
    with:
      toolchain: ${{ inputs.toolchain }}
      additional_cache_path: ${{ inputs.additional_cache_path }}
      additional_cache_key: ${{ inputs.additional_cache_key }}
      additional_cache_miss: ${{ inputs.additional_cache_miss }}
      additional_script: ${{ inputs.additional_script }}
      required_packages: ${{ inputs.required_packages }}
      workspaces: ${{ inputs.workspaces }}
      additional_args: ${{ inputs.additional_args }}
      working-directory: ${{ inputs.working-directory }}
      custom_cargo_commands: ${{ inputs.custom_cargo_commands }}
      login_private_registry: ${{ inputs.publish_public_registry != 'true' }}
      test-publish-required: ${{ inputs.force_nonrequired_publish_test == 'false' && (inputs.publish_docker == 'true' || inputs.publish_private_registry == 'true' || inputs.publish_public_registry == 'true') }}
      skip-tests-no-changes: ${{ inputs.skip-tests-no-changes }}
      skip-miri-test: ${{ inputs.skip-miri-test }}
      nightly_toolchain: ${{ inputs.miri_toolchain }}
    secrets: inherit
  publish_private_registry:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust_private_registry_publish.yml@v1
    if: always() && inputs.publish == 'true' && inputs.publish_private_registry == 'true' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs:
      - test
    with:
      toolchain: ${{ inputs.toolchain }}
      additional_script: ${{ inputs.additional_script }}
      required_packages: ${{ inputs.required_packages }}
      working-directory: ${{ inputs.working-directory }}
      additional_args: ${{ inputs.additional_args }}
      custom_cargo_commands: ${{ inputs.custom_cargo_commands }}
    secrets: inherit
  publish_public_registry:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust_public_registry_publish.yml@v1
    if: always() && inputs.publish == 'true' && inputs.publish_public_registry == 'true' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs:
      - test
    with:
      toolchain: ${{ inputs.toolchain }}
      additional_script: ${{ inputs.additional_script }}
      required_packages: ${{ inputs.required_packages }}
      working-directory: ${{ inputs.working-directory }}
      additional_args: ${{ inputs.additional_args }}
      custom_cargo_commands: ${{ inputs.custom_cargo_commands }}
    secrets: inherit
  publish_docker:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/docker_publish.yml@v1
    if: always() && inputs.publish == 'true' && inputs.publish_docker == 'true' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs:
      - test
    with:
      working-directory: ${{ inputs.working-directory }}
      docker-context: ${{ inputs.docker-context }}
      dockerfile: ${{ inputs.dockerfile }}
      image: ${{ inputs.docker_image }}
      registry: ${{ inputs.docker_registry }}
    secrets: inherit
  publish_binary:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/rust_binary_publish.yml@v1
    if: always() && inputs.publish == 'true' && inputs.publish_binary == 'true' && (needs.test.result == 'success' || needs.test.result == 'skipped')
    needs:
      - test
    with:
      toolchain: ${{ inputs.toolchain }}
      release_channel: ${{ inputs.release_channel }}
      additional_script: ${{ inputs.additional_script }}
      required_packages: ${{ inputs.required_packages }}
      working-directory: ${{ inputs.working-directory }}
      additional_args: ${{ inputs.additional_args }}
      custom_cargo_commands: ${{ inputs.custom_cargo_commands }}
      matrix_file: ${{ inputs.matrix_file }}
      post_build_additional_script: ${{ inputs.post_build_additional_script }}
      sign_build: ${{ inputs.binary_sign_build }}
    secrets: inherit
  should_report_release:
    runs-on: ubuntu-latest
    if: always()
    outputs:
      report: ${{ steps.report.outputs.result }}
    needs:
      - publish_private_registry
      - publish_public_registry
      - publish_docker
      - publish_binary
    steps:
      - uses: actions/github-script@v7
        name: Report status on PR
        id: report
        with:
          result-encoding: string
          script: |
            if (!${{ inputs.report_release }}) {
              return "false";
            }
            if (!${{ inputs.publish }}) {
              return "false";
            }
            if (${{ contains(needs.*.result, 'failure') }}) {
              return "false";
            }
            if (${{ contains(needs.*.result, 'cancelled') }}) {
              return "false";
            }
            const releases = [
              [${{ inputs.publish_private_registry }}, ${{ needs.publish_private_registry.outputs.released || 'false' }}],
              [${{ inputs.publish_public_registry }}, ${{ needs.publish_public_registry.outputs.released || 'false' }}],
              [${{ inputs.publish_docker }}, ${{ needs.publish_docker.outputs.released || 'false' }}],
              [${{ inputs.publish_binary }}, ${{ needs.publish_binary.outputs.released || 'false' }}],
            ];
            return releases.filter(release => release[0] && release[1]).length > 0 ? "true" : "false";

  report_release:
    needs:
      - publish_private_registry
      - publish_public_registry
      - publish_docker
      - publish_binary
      - should_report_release
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/gh-release-when-published.yaml@v1
    if: always() && needs.should_report_release.outputs.report == 'true'
    with:
      working-directory: ${{ inputs.working-directory }}
      private_registry_release: ${{ inputs.publish_private_registry == 'true' && needs.publish_private_registry.outputs.released == 'true' }}
      public_registry_release: ${{ inputs.publish_public_registry == 'true' && needs.publish_public_registry.outputs.released == 'true' }}
      docker_release: ${{ inputs.publish_docker == 'true' && needs.publish_docker.outputs.released == 'true' }}
      binary_release: ${{ inputs.publish_binary == 'true' && needs.publish_binary.outputs.released == 'true' }}
    secrets: inherit
