name: Publish Release to Private Registry

on:
  workflow_call:
    outputs:
      released:
        description: Was the crate released
        value: "true"
    inputs:
      additional_args:
        type: string
        default: ""
        description: Additional arguments to pass to the cargo command
      toolchain:
        type: string
        default: "1.73"
        description: Rust toolchain to install
      working_directory:
        type: string
        default: "."
        description: Working directory to run the cargo command
      additional_script:
        type: string
        default: ""
        description: Additional script to run before the additional packages
      custom_cargo_commands:
        type: string
        default: ""
        description: Cusom cargo commands that will be run after login
    secrets:
      github-private-keys:
        required: false
        description: Private keys that need to be added to the ssh-agent

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_HTTP_USER_AGENT: "shipyard ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}"

jobs:
  derive_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: "rust-toolchain.toml"
      - name: Get rust channel
        id: rust-channel
        shell: bash
        run: |
          rust_version="$(yq -p toml '.toolchain.channel' < rust-toolchain.toml || echo '${{ inputs.toolchain }}')"
          rust_version="${rust_version/./-}"
          echo "rust_version=${rust_version}" >> $GITHUB_OUTPUT
    outputs:
      rust-channel: ${{ steps.rust-channel.outputs.rust_version }}
  cargo_publish_private_registry:
    needs:
      - derive_runner
    name: Release new version to private registry
    runs-on: "rust-${{ needs.derive_runner.outputs.rust-channel }}-scale-set"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          env-vars: ""
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.toolchain }}
      - uses: ForesightMiningSoftwareCorporation/github/.github/actions/login-private-registry@v1
        with:
          private_key: ${{ secrets.CARGO_PRIVATE_REGISTRY_SSH_PRIVATE_KEY }}
          host: ${{ secrets.CARGO_PRIVATE_REGISTRY_HOST }}
          name: ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }}
          token: ${{ secrets.CARGO_PRIVATE_REGISTRY_TOKEN }}
          additional_private_keys: |
            ${{ secrets.FSE_SSH_PRIVATE_KEY }}
            ${{ secrets.VOLUMESIGHT_SSH_PRIVATE_KEY }}
      - name: Additional Script
        if: inputs.additional_script != ''
        run: ${{ inputs.additional_script }}
        shell: bash
      - name: Update Packages
        if: inputs.required_packages != ''
        run: sudo apt-get update -yq && sudo apt-get install -yq --no-install-recommends ${{ inputs.required_packages }}
      - name: Run custom cargo command
        if: inputs.custom_cargo_commands != ''
        shell: bash
        working-directory: ${{ inputs.working_directory }}
        run: ${{ inputs.custom_cargo_commands }}
      - name: Publish to private registry
        shell: bash
        working-directory: ${{ inputs.working_directory }}
        run: cargo publish --registry ${{ secrets.CARGO_PRIVATE_REGISTRY_NAME }} ${{ inputs.additional_args }}
