on:
  workflow_call:
    outputs:
      matrix:
        description: "Usable matrix"
        value: ${{ jobs.matrix.outputs.matrix }}

jobs:
  matrix:
    name: Build Matrix for next jobs
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create and set Build Matrix from matrix.json
        id: set-matrix
        run: |
          TASKS=$(jq -c . < ${{ github.workspace }}/.github/workflows/matrix.json | tr -d '^J')
          echo "{matrix}={$TASKS}" >> $GITHUB_OUTPUT