on:
  workflow_call:
    inputs:
      rust_versions:
        type: string
        default: "1.69"
        description: Rust rust_versions to install, whitespace separated

jobs:
  check-existing-rust-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check for existing images
        id: check
        run: |
          requested_versions=(${{ inputs.rust_versions }})
          required_versions=''
          for version in "${requested_versions[@]}"; do
            docker manifest inspect ghcr.io/foresightminingsoftwarecorporation/rust-test:$version > /dev/null || \
            required_versions+=",\"$version\""
          done
          echo "matrix=[\"none\"${required_versions}]" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.check.outputs.matrix }}

  build-rust-test-images:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/build_rust_test_images.yaml@v1
    needs: check-existing-rust-versions
    strategy:
      matrix:
        version: ${{ fromJson(needs.check-existing-rust-versions.outputs.matrix) }}
    with:
      rust_version: ${{ matrix.version }}
    secrets: inherit
