name: Auto tag repo for use in reusable workflows
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Name of the tag to create'
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag branch
        run: |
          git tag -f ${{ github.event.inputs.tag_name }}
          git push -f origin ${{ github.event.inputs.tag_name }}
