name: Update Release workflows
on:
  workflow_call:

jobs:
  generate_release_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - id: generate_token
        name: Generate token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.FMSC_BOT_GITHUB_APP_ID }}
          private_key: ${{ secrets.FMSC_BOT_GITHUB_APP_PRIVATE_KEY }}
      - name: Install FSLABScli
        uses: ForesightMiningSoftwareCorporation/fslabscli-action@v1
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - id: generate_workflow
        name: Generate updated workflows
        shell: bash
        working-directory: .
        run: |-
          template_path=".github/workflows/release.template"

          if [ -e "$template_path" ]; then
            template_option="--template $template_path"
          else
            template_option=""
          fi
          fslabscli generate-release-workflow --output .github/workflows/test.yml ${template_option} --test-publish-required-disabled --output-release .github/workflows/release_publish.yml
      - id: derive_branch_name
        name: Derive branch name
        shell: bash
        working-directory: .
        run: |
          branch_name="${{ github.base_ref || github.ref }}"
          echo "branch_name=ci/update-ci-workflows-${branch_name##*/}" >> "$GITHUB_OUTPUT"

      - name: Create Pull request with new ci
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: "chore: update release and test pipelines"
          branch: ${{ steps.derive_branch_name.outputs.branch_name }}
          delete-branch: true
          title: "chore: update release and test pipelines"
          labels: ci
          body: |
            Release workflows needs updating
          team-reviewers: Infra
          add-paths: |
            .github/workflows/test.yml
            .github/workflows/release_publish.yml
      - name: Mark PR as auto-mergeable
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
